### ISSUE TITLE
Variable name bug

### ISSUE THREAD

**Issue by tiavlovskiegor24** [bioinfocao/pysapc#1]
Please, correct the spelling error (prefernce -> preference) in file SparseAPCluster.py

Lines:
https://github.com/bioinfocao/pysapc/blob/25597fa42762b30711e57cd94213c81f6104cb65/pysapc/SparseAPCluster.py#L101

https://github.com/bioinfocao/pysapc/blob/25597fa42762b30711e57cd94213c81f6104cb65/pysapc/SparseAPCluster.py#L108

https://github.com/bioinfocao/pysapc/blob/25597fa42762b30711e57cd94213c81f6104cb65/pysapc/SparseAPCluster.py#L398

https://github.com/bioinfocao/pysapc/blob/25597fa42762b30711e57cd94213c81f6104cb65/pysapc/SparseAPCluster.py#L434

**Comment by bioinfocao** [comment]
Replaced. Thanks.
